image:
  name: alpine/helm:3.5.2
  entrypoint: ["/bin/sh", "-c"]

variables:
  HELM_EXPERIMENTAL_OCI: 1

stages:
  - lint-helm-chart
  - release-helm-chart

lint-helm:
  stage: lint-helm-chart
  script:
    - helm lint .

release-helm:
  stage: release-helm-chart
  script:
    - echo $CI_BUILD_TOKEN |
      helm registry login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
    - helm chart save . ${CI_REGISTRY}/${CI_PROJECT_PATH}:$CI_COMMIT_TAG
    - helm chart push ${CI_REGISTRY}/${CI_PROJECT_PATH}:$CI_COMMIT_TAG
  only:
    - tags