{{- define "common.servicemonitor" -}}
{{- if ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) }}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    ServiceMonitor: {{ .Release.Name | quote }}
spec:
  targetLabels:
  - cluster
  jobLabel: {{ .Values.name }}
  selector:
    matchLabels:
      k8s-monitoring: "true"
      release: {{ .Release.Name | quote }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: {{ .Values.servicemonitor.portName | default "http" }}
    honorLabels: true
    scheme: http
    path: {{ .Values.servicemonitor.path | default "/metrics" }}
    interval: 60s
{{- end -}}
{{- end }}
{{- end -}}